### ISSUE TITLE
Add Kafka consumer auto-deletion on timeout

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-bridge#101]
An HTTP client can create a Kafka consumer which stay alive for subsequent calls for polling messages.
The consumer can be deleted only with an HTTP DELETE sent by the HTTP client when it doesn't need the consumer anymore.
It's useful having a consumer auto-deletion on timeout; if it's not used for a certain amount of time it's automatically deleted by the bridge without waiting for the explicit HTTP DELETE from an HTTP client.

**Comment by stanlyDoge** [comment]
I was looking at some possible ways how to implement this. So far I (and Paolo) found two possible solutions. One of them is to use a map `<consumerID, id>`, where `id` is the identity of related timer.
```
// action cooperating with consumer
vertx.cancelTimer(map.get(consumerID));
map.put(consumerID, vertx.setTimer(timeout));
```

Another approach is to have a map `<consumerID, timestamp>` and use `vertx.setPeriodic(long, handler)` to loop through this map and delete all the consumers, whose timestamp is too old.
```
// action cooperating with consumer
map.replace(consumerID, date());

//main loop
vertx.setPeriodic(1000, a -> {
     if (map.get(consumerId) < date() + timeout)
        deleteConsumer();
     });
```

What do you guys think is a better approach and why? @ppatierno @scholzj @tombentley

**Comment by ppatierno** [comment]
After initial thoughts about one timer per consumer, I started to be scared about the number of timers we could have for more consumers and concerns about how to deal with them (even from a Vert.x pov).
Having just one-timer has the drawback of having an action maybe every second checking the map of consumers to find which is "old". Doing this operation every second (or we can decide the timing) on a long list of consumers is time-consuming as well.

@stanlyDoge in the second solution snippet you have to go through the entire map finding which consumer is "old", you don't have a `consumerId` when the timer is raised.

**Comment by stanlyDoge** [comment]
Yeah, that is just minimal code.

**Comment by tombentley** [comment]
I think a single periodic timer should be fine. This mechanism is really about providing a way to deal with ill-behaving clients (because we expect client applications to usually close their consumer explicitly), so I don't think the time the consumer actually gets closed needs to be predictable, and a single periodic timer should scale better than a timer per consumer. I don't think this periodic timer would need to run regularly, but how often it runs should probably depend on the configured timeout.

We should probably arrange to log at INFO or maybe even WARN level when we have to close a consumer, since it can indicate poorly coded clients.
