### ISSUE TITLE
Consumer request timeout during subscription is not honored.

### ISSUE THREAD

**Issue by nishantkarve** [strimzi/strimzi-kafka-bridge#368]
While creating a consumer group and a consumer within that group the following is passed
```
{
    "name": "some-consumer",
    "auto.offset.reset": "earliest",
    "format": "json",
    "enable.auto.commit": false,
    "fetch.min.bytes": 512,
    "consumer.request.timeout.ms": 30000
  }
```
**"consumer.request.timeout.ms"** should keep the http/https connection between the consumer and the bridge open for that duration in ms. However, the connection closes as soon as the data is consumed by the bridge. The expectation is that the http/https connection stays open for 30s until the set timeout is reached OR the **fetch.min.bytes** property is achieved. 

The application properties file of the bridge also has the following. Does setting this property overrides anything that's set during subscription?
```
#Sets the maximum amount of time, in milliseconds, for the consumer to wait for messages for a request. If the timeout period is reached without a response, an error is returned.
kafka.consumer.consumer.request.timeout.ms=30000
```
The application property file also has 
```
#Sets the minimum ammount of data, in bytes, for the consumer to receive. The broker waits until the data to send exceeds this amount.
kafka.consumer.fetch.min.bytes=20971520
```
Does this override the **"fetch.min.bytes"** property from the subscription request as well?

Thanks in advance

**Comment by ppatierno** [comment]
Regarding the "override" question, every configuration parameter provided on consumer creation using the above JSON, will override the related parameters in the properties file.

Regarding the "consumer.request.timeout.ms" and the fact that it should keep the connection opened for its duration and "fetch.min.bytes" waiting for minimum bytes to receive, the bridge is acting as a native Kafka consumer.
It means that:

* because on every GET on `/records` endpoint it does a "poll", the broker replies to that request (even with empty records) so the "consumer.request.timeout.ms" is honored because it's mostly related on network problems when the broker doesn't reply in that time. In order to achieve what you want you can use the `timeout` query parameter when doing the GET; it actually is used as timeout for the internal "poll", blocking the poll (so leaving connection opened) if no data are available.
* regarding "fetch.min.bytes", it's more a piece of information for the broker which means "please don't send me data if there aren't min bytes I want". It means that the broker could have messages to deliver to the consumer but the total size doesn't reach the minimum requested, so the broker just replies with no records.

Said that I could understand that at this point, from a REST API point of view, the "consumer.request.timeout.ms" seems to be useless from the HTTP client perspective. We could change a little bit of its behavior in the bridge in order to use it as actual poll timeout (or at least the minimum specified with this parameter and the above mentioned `timeout` query parameter). Of course, it changes the meaning of "consumer.request.timeout.ms" from a native Kafka client point of view but would make sense from a REST API point of view.

Regarding "fetch.min.bytes" it could mean not providing this parameter to the broker (leaving default value "1") but using it internally and buffering messages in the bridge then delivering them when the min bytes is reached. My only concern about that and the reason why there is no buffering in the bridge is about memory consumption when the bridge starts to handle more and more consumers. Anyway, it's something we can think of.

Any thoughts on your side?

**Comment by nkarw** [comment]
I forgot to mention that I used the `timeout` query parameter with the `/records` API. What I noticed is that as soon as the subscribed kafka topic gets a message it's delivered to the bridge and the connection is gracefully closed. My understanding is that the messages will accrue/buffer in the bridge until it reaches the `timeout` value or the `"fetch.min.bytes"` is reached after which the bridge will consume the messages. I do understand that setting the `timeout` value too high could cause memory issues on the bridge during a peak load.

**Comment by ppatierno** [comment]
The long polling stuff is a question asked by another user as well and the solution that we have today is using the `timeout` query parameter. It allows you to have the HTTP connection for more time when data are not available but the bridge returns data and close the connection as soon as messages come from the broker and send them to the client (you already mentioned that).

Anyway, if you play with the `fetch.min.bytes` parameter you should be able to avoid that.
As I mentioned earlier this parameter is an information for the broker. The default parameter is 1 and it means that as soon as a message is available the broker returns something and the bridge close the connection. If you set `fetch.min.bytes` to 512 for example and the `timeout` parameter at 60 seconds what should happen is the following:

* if the broker has for example 10 messages to deliver but the total is less than 512 bytes, there are not delivered to the bridge so not to the client as well and the connection is still in place in the 60 secs timeout. When the broker reaches the 512 bytes to deliver, it sends the messages to the bridge so the client and the connection is closed.
* if the timeout expires and no messages are delivered the connection is closed anyway

> The idea is to make each HTTP(s) request count in terms of data returned

It sounds to me setting a quite long timeout and playing a little bit with the `fetch.min.bytes` as well.

> My understanding is that the messages will accrue/buffer in the bridge until it reaches the timeout value or the "fetch.min.bytes" is reached after which the bridge will consume the messages

The bridge doesn't do any kind of buffering as I mentioned early. When playing with the `fetch.min.bytes` you are saying to the Kafka broker to not send messages until that limit is reached.

Finally, about autoscaling. It's not so simple. The HTTP bridge is a kind of stateless. If you are running on Kubernetes you cannot just scale the number of replicas in the Deployment.
A consumer is created on a specific bridge instance and it has to connect to THAT instance for doing all the operations (records, offsets, seek, ...). So on Kubernetes the first way of scaling is having more Deployments but with 1 replica. You could then put an API gateway / reverse proxy in front of it. We did some tests with the 3scale one.

**Comment by nkarw** [comment]
Thanks for the comments. Very helpful. Will play with consumer timeout and min bytes to come to a sweet spot.

The stateless part of the architecture actually drives me towards autoscaling more than anything else. I do get the affinity of a consumer to a bridge instance and it might not be easy to scale that instance of the bridge itself. 

What's the highest number of transactions per second you achieved through 3Scale?

**Comment by ppatierno** [comment]
We didn't do a load testing but just a test about the routing rules from the 3scale gateway to the right bridge instances.

**Comment by quickbooks2018** [comment]
https://www.youtube.com/watch?v=1Bv5SQW0BjI&t=336s&ab_channel=cloudgeeksinc

**Comment by ppatierno** [comment]
@nishantkarve is this issue something that you are still looking at or we can close it?

**Comment by ppatierno** [comment]
@nishantkarve going to close it because not hearing from you since years. Feel free to re-open if something still interesting for you.
