### ISSUE TITLE
Http and Https schemes not honored in the response

### ISSUE THREAD

**Issue by nishantkarve** [strimzi/strimzi-kafka-bridge#372]
I have placed the Strimzi bridge behind an NGINX reverse proxy, which is fronted by an AWS ALB. The communication between the ALB and NGINX is in "https" and between the NGINX proxy and the Strimzi bridge is in "HTTP", since they will be on the same EC2 instances. 

The "base_uri" is returned in the body of the request which always returns "http" irrespective of the original request scheme that was used by the client ("https"). This will cause the clients to use "https" for the initial request but "http" for subsequent calls to subscribe to topics. 

Hope that helps. I can provide some examples if needed.

**Comment by nkarw** [comment]
Never mind. I fixed this issue on the NGINX side by substituting the outgoing response with "https". A kludgy fix, but works nevertheless. 
Thanks

**Comment by scholzj** [comment]
I guess this should be fixed anyway. I think @ppatierno had this working in the past - mayb enginx needs some additional configuration to pass the original protocol?

**Comment by ppatierno** [comment]
Yeah, the bridge is able to handle the [Forwarded](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) header for that. Can you please increase the bridge logging level to "DEBUG", it should provide the entire HTTP request going to the bridge and we can check if that header is provided by Nginx. I am really interested in it.

**Comment by nkarw** [comment]
I see the following in the Strimzi logs after setting it to DEBUG. Is there anything specific we are looking for?

headers = 
```
Host: localhost:443
Connection: close
Content-Length: 167
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
Cache-Control: no-cache
Origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
Postman-Token: 3be7b83e-dce3-1d53-2941-01267b5a69e2
Content-Type: application/vnd.kafka.v2+json
Accept: */*
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
```

**Comment by nkarw** [comment]
I see what you were requesting. The X-Forwarded for. I haven't configured that in NGINX. Let me try doing that and see if the proxy forwards the headers to NGINX. I will update you shortly.

My apologies. I clicked the "forwarded" link after I posted my previous message.

**Comment by nkarw** [comment]
And you were right. Here is the log after passing the X-Forwarded for. One question I have for you though. If the X-Forwarded for has the "https" passed from the proxy to the upstream (Strimzi) as seen in the header, do you use that same scheme in the "base_uri" returned to the user?

headers = 
```
Host: localhost:443
**X-Forwarded-For: 127.0.0.1
X-Forwarded-Proto: https**
Connection: close
Content-Length: 167
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36
Cache-Control: no-cache
Origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
Postman-Token: e57dcc75-fdfb-b9fa-c44c-c19560431bdb
Content-Type: application/vnd.kafka.v2+json
Accept: */*
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9 
```

**Comment by ppatierno** [comment]
Yes exactly, that is why we added the forwarded headers support.

**Comment by nkarw** [comment]
Don't be sorry. We are all occupied. :)

I was trying to bold the "X-Forwarded-For" in the comment so you could notice them readily...They are not like that in the original log. :)

I tested by removing the working NGINX hack I added for substituting the http to https. I can share that file with you, if required. 

The test failed even if I do the X-Forwarded for. I get back my base_uri in http instead of https. That's why I added the hack through NGINX. Ideally, I would like that to be handled by the bridge itself.

Also, it seems the bridge has some sort of "sessions" held up  if I have 2 Strimzi bridges running at 2 different ports on the same machine and local balanced by NGINX. My request for subscription was handled by one instance and when I used the base_uri again and the request was routed to another instance it errored out with the following.
`Consumer instance not found  `

**Comment by ppatierno** [comment]
About the bridge returning the http instead of the https it's quite strange. Can you provide step to reproduce it using Nginx.

Regarding the second question, it's normal. The bridge instance is "stateful" in the sense that when you create a consumer on a bridge instance, the HTTP consumer has to send the HTTP request to that instance and not a different one. This is how the Kafka protocol work: on the bridge a Kafka consumer instance is created, joining a group, being part of rebalancing and so on.

**Comment by nkarw** [comment]
Sorry for the delayed response. I am not facing the issue anymore. It was an error on my part.

With the understanding that the bridge is stateful, has your team given any thought on scaling the bridge, preferably auto scaling it? Is that somewhere on the product roadmap?

**Comment by ppatierno** [comment]
As you can understand it's not so simple doing an auto-scaling for the bridge due to the problems we already talked about. Each bridge instance is completely different from the others and it has its own state, it's not just one more replica. We don't have such a feature on our roadmap but it's always interesting to listen from the community ideas or thoughts.

**Comment by ppatierno** [comment]
@nishantkarve as mentioned by you in one of the latest comment, this is not an issue but an error on your part, so I am going to close this one.
