### ISSUE TITLE
Support to deploy RedPanda instead of Kafka server?

### ISSUE THREAD

**Issue by sebasmagri** [strimzi/strimzi-kafka-bridge#590]
We've been evaluating RedPanda for a while and haven't found issues running it pretty much as a drop in replacement for Kafka. However in order to move into our production envs we would like to keep using the strimzi operator to manage it along with our kafka connect set up.

Would deploying RedPanda instead of Kafka be something that the project could be interested on supporting?

**Comment by scholzj** [comment]
I'm not completely sure what are you asking about, especially since you opened this in the Bridge repository. 

As for the Bridge (but at the end for Connect it would be the same), it uses the Kafka protocol as implemented by the official Kafka clients and it is tested against Apache Kafka brokers. In theory, it should work with RedPanda - but how well it would work depends mainly on how well did they implement the Kafka protocol and its semantics / behaviours.

As for supporting RedPanda instead of Kafka, there are no plans for this. And it might not even be possible due to licensing issues etc.

**Comment by sebasmagri** [comment]
I'm so sorry, I didn't realize I was in the bridge repo still. Would you think it's worth opening an issue in the operator repo as of something to consider?

**Comment by scholzj** [comment]
No worries about the repo. I just wasn't sure about which exact part are you asking. My personal view is that we have no interest to support RedPanda. Both from the licensing perspective mentioned above, but we also do not have resources for it. It is not like you _plug it in instead of Kafka_. It is a different software which requires different ops processes etc. If you want, feel free to open the issue in the operators repo, but I do not think the outcome will be different.
